name: Lint

on:
  pull_request:

env:
  FORCE_COLOR: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-check
          eslint_flags: 'src/'


  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm
      - run: npm test
